service: parking-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  architecture: x86_64
  memorySize: 512
  timeout: 10
  environment:
    DATABASE_URL: ${aws:ssm:/parking/DATABASE_URL}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    fileName: requirements.txt        # at repo root
    dockerizePip: true                # needs Docker Desktop running; set to false if you don't have it
    slim: false
    strip: false                      # keep native libs (e.g., pydantic-core)
    layer: true                       # put deps in a dedicated Lambda Layer
    invalidateCaches: true
    pipCmdExtraArgs:
      - --no-cache-dir
      - --upgrade
      - --force-reinstall

package:
  individually: true                  # package each function separately
  # Global excludes (belt-and-suspenders)
  patterns:
    - '!frontend/**'
    - '!**/.git/**'
    - '!**/.github/**'
    - '!**/.serverless/**'
    - '!**/__pycache__/**'
    - '!**/.pytest_cache/**'
    - '!**/tests/**'
    - '!**/node_modules/**'
    - '!**/*.map'
    - '!**/*.log'

functions:
  api:
    handler: backend/app/main.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    # Function-level packaging: exclude everything, then explicitly include backend
    package:
      patterns:
        - '!**/*'            # start from empty
        - 'backend/**'       # include only backend app code
        # (requirements.txt is NOT needed in the function bundle since deps are in the layer)