"""init tables

Revision ID: 61209d9166b0
Revises: 
Create Date: 2025-09-10 21:19:21.515417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61209d9166b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_spaces', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('asof', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('series', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupancy_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occupied', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupancy_snapshots_lot_id'), 'occupancy_snapshots', ['lot_id'], unique=False)
    op.create_index(op.f('ix_occupancy_snapshots_ts'), 'occupancy_snapshots', ['ts'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occupied_count', sa.Integer(), nullable=False),
    sa.Column('total_spaces', sa.Integer(), nullable=False),
    sa.Column('inference_ms', sa.Integer(), nullable=True),
    sa.Column('battery_pct', sa.Float(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_ts'), 'detections', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_ts'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_occupancy_snapshots_ts'), table_name='occupancy_snapshots')
    op.drop_index(op.f('ix_occupancy_snapshots_lot_id'), table_name='occupancy_snapshots')
    op.drop_table('occupancy_snapshots')
    op.drop_table('forecasts')
    op.drop_table('devices')
    op.drop_table('lots')
    # ### end Alembic commands ###
